<?php

namespace AppBundle\Entity;

/**
 * personaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class personaRepository extends \Doctrine\ORM\EntityRepository
{
}
