<?php

namespace AppBundle\Entity;

/**
 * reservaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reservaRepository extends \Doctrine\ORM\EntityRepository
{
}
