<?php

namespace AppBundle\Entity;

/**
 * caracteristicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class caracteristicaRepository extends \Doctrine\ORM\EntityRepository
{
}
