<?php

namespace AppBundle\Entity;

/**
 * casaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class casaRepository extends \Doctrine\ORM\EntityRepository
{
}
