<?php

namespace AppBundle\Entity;

/**
 * casa_caracteristicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class casa_caracteristicaRepository extends \Doctrine\ORM\EntityRepository
{
}
