<?php

namespace AppBundle\Entity;

/**
 * estadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class estadoRepository extends \Doctrine\ORM\EntityRepository
{
}
